FROM dorowu/ubuntu-desktop-lxde-vnc:bionic

RUN sudo apt-get update \
  && sudo apt-get update \
  && sudo apt-get install gpg-agent -y \
  && sudo apt autoremove \
  && sudo apt-get install wget -y \
  && wget -O - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add - \
  && sudo add-apt-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./' \
  && sudo apt-get update \
  && sudo dpkg --add-architecture i386 \
  && wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add - \
  && sudo apt-get update --fix-missing -y \
  && sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' \
  && sudo apt-get update \
  && sudo apt install winehq-stable -y
