FROM foundworld/ubuntu-desktop-wine:0.1

RUN sudo apt-get remove winetricks

RUN sudo mkdir /wine-temp \
  && cd /wine-temp \
  && wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
  && sudo chmod +x winetricks \
  && sudo mv -v winetricks /usr/local/bin
  
RUN sudo apt-get install cabextract -y \
  && sudo apt-get intall p7zip-full -y
